# Generated by Django 3.2.5 on 2021-09-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='poistion',
            new_name='position',
        ),
    ]
