# Generated by Django 3.2.5 on 2021-09-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_rename_poistion_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fburl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='instaurl',
            field=models.URLField(blank=True),
        ),
    ]
