# Generated by Django 3.2.5 on 2021-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20210917_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposition', models.CharField(max_length=30)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
