# Generated by Django 3.2.5 on 2021-09-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_matches_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='mygoals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='oppositiongoals',
            field=models.IntegerField(null=True),
        ),
    ]
