# Generated by Django 3.2.5 on 2021-09-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20210917_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='mygoals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='oppositiongoals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
