# Generated by Django 3.2.5 on 2021-09-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20210918_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
