# Generated by Django 3.2.5 on 2021-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_alter_matches_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateField(),
        ),
    ]
