# Generated by Django 3.2.5 on 2021-09-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_alter_matches_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
