# Generated by Django 3.2.5 on 2021-09-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='frstimg',
            new_name='homeimage',
        ),
        migrations.RemoveField(
            model_name='images',
            name='scndimg',
        ),
    ]
