# Generated by Django 3.2.5 on 2021-09-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_auto_20210923_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
