# Generated by Django 3.2.5 on 2021-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_rename_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='club/images/')),
                ('name', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=40)),
            ],
        ),
    ]
