# Generated by Django 3.2.5 on 2021-10-01 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='doj',
            field=models.DateField(),
        ),
    ]
